import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ActiveLink } from "@/ui/atoms/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Products",
	// description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="pl">
			<body className={inter.className}>
				<nav role="navigation">
					<ul className="mx-4 mt-2 flex justify-end gap-3">
						<li className="cursor-pointer text-blue-300 hover:text-blue-600">
							<ActiveLink href="/" exact>
								Home
							</ActiveLink>
						</li>
						<li className="cursor-pointer text-blue-300 hover:text-blue-600">
							<ActiveLink href="/products" exact>
								All
							</ActiveLink>
						</li>
					</ul>
				</nav>
				<section className="lg:max-w-7x; mx-auto max-w-md p-12 text-center sm:max-w-2xl sm:py-16 md:max-w-4xl">
					{children}
				</section>
				<footer>
					<p className="text-center text-sm text-gray-500">Footer 2023®</p>
				</footer>
			</body>
		</html>
	);
}
